from numpy import nan


ANNOTATION_ASSET = {
        # older than the excel asset used to upload in file_listing_block
        'timestamp': 1582890700,
        'report_data': [
            {
                u'Origin': u'portal',
                'responsible': 'hugo',
                u'Creator': u'fieda',
                u'Destination': u'finanzgeschaefte',
                'is_done': True,
                u'Error Message': u'No error occurred',
                u'Review State': u'bl_workflow--STATUS--entwurf',
                u'Content Type': u'Unknown content type',
                u'Status Code': nan,
                u'Response Time': u'Unknown response time',
                u'Internal/External': u'Internal Link',
                },
            {
                u'Origin': u'portal',
                'responsible': nan,
                u'Creator': u'helga',
                u'Destination': u'stadtverwaltungsunterhaltsplaene',
                'is_done': True,
                u'Error Message': u'No error occurred',
                u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                u'Content Type': u'Unknown content type',
                u'Status Code': nan,
                u'Response Time': u'Unknown response time',
                u'Internal/External': u'Internal Link',
                },
            {
                u'Origin': u'portal',
                'responsible': 'hugo',
                u'Creator': u'hildegard',
                u'Destination': u'amtsverhandlungen',
                'is_done': False,
                u'Error Message': u'No error occurred',
                u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                u'Content Type': u'Unknown content type',
                u'Status Code': nan,
                u'Response Time': u'Unknown response time',
                u'Internal/External': u'Internal Link',
                },
            {
                u'Origin': u'portal',
                'responsible': nan,
                u'Creator': u'adminanna',
                u'Destination': u'omnibus-planungsstelle',
                'is_done': False,
                u'Error Message': u'No error occurred',
                u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                u'Content Type': u'Unknown content type',
                u'Status Code': nan,
                u'Response Time': u'Unknown response time',
                u'Internal/External': u'Internal Link',
                },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'uschi',
                    u'Destination': u'antipattern-in-der-informatik',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': nan,
                    u'Response Time': u'Unknown response time',
                    u'Internal/External': u'Internal Link',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'alfred',
                    u'Destination': u'http://www.2phasen.ch',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--entwurf',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 301.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'anneliese',
                    u'Destination': u'http://www.2-phasen.ch',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 301.0,
                    u'Response Time': 2,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'fritz',
                    u'Destination': u'http://fuehrerausweise.ch/informationen/fak/'
                    ,
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 301.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'peter',
                    u'Destination': u'http://www.ilv.ch',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 301.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'hugo',
                    u'Destination': u'http://home.gibm.ch/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 301.0,
                    u'Response Time': 2,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'helga',
                    u'Destination': u'http://ict-berufsbildung.ch/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 301.0,
                    u'Response Time': 3,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'hildegard',
                    u'Destination': u'http://berufsmaturbb.ch/index.php?id=2',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--entwurf',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 301.0,
                    u'Response Time': 2,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'adminanna',
                    u'Destination': u'http://www.Lausinfo.ch',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 301.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'berta',
                    u'Destination': u'http://www.epschaenzli.ch/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 301.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'uschi',
                    u'Destination': u'http://www.baselland-shop.ch',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 302.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'alfred',
                    u'Destination': u'http://www.wahlen.bl.ch/de/vote/list/2016/06/05'
                    ,
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 302.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'anneliese',
                    u'Destination': u'http://www.wahlen.bl.ch/de/vote/list/2016/06/05'
                    ,
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 302.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'fritz',
                    u'Destination': u'http://www.igkg-beiderbasel.ch/index.php/bueroassistent-in'
                    ,
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--entwurf',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 302.0,
                    u'Response Time': 2,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'peter',
                    u'Destination': u'http://www.statistik.bl.ch/web_portal/9_1',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 302.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'hugo',
                    u'Destination': u'http://www.statistik.bl.ch/web_portal/13_2',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 302.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'helga',
                    u'Destination': u'http://www.statistik.bl.ch/web_portal/1_1_1',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 302.0,
                    u'Response Time': 2,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'hildegard',
                    u'Destination': u'https://www.entwicklung.bs.ch/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 303.0,
                    u'Response Time': 3,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'adminanna',
                    u'Destination': u'https://www.aue.bs.ch/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 303.0,
                    u'Response Time': 2,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'berta',
                    u'Destination': u'http://www.umweltberichtbeiderbasel.ch/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--entwurf',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 303.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'uschi',
                    u'Destination': u'https://www.umweltberichtbeiderbasel.bs.ch/indikatoren/indikatoren-uebersicht.html'
                    ,
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 303.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'alfred',
                    u'Destination': u'https://www.blkb.ch/newhome',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 303.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'anneliese',
                    u'Destination': u'https://www.stiftung-mercator.ch/de/foerderung/'
                    ,
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 307.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'fritz',
                    u'Destination': u'http://www.energiepaket-bl.ch/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 307.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'peter',
                    u'Destination': u'https://www.lignumregionbasel.ch/agenda/anmeldeformular/'
                    ,
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 307.0,
                    u'Response Time': 2,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'hugo',
                    u'Destination': u'http://www.baselland-tourismus.ch/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--entwurf',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 307.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'helga',
                    u'Destination': u'http://elmar.swisstph.ch/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 307.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'hildegard',
                    u'Destination': u'http://www.bricklive.ch',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 308.0,
                    u'Response Time': 2,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'adminanna',
                    u'Destination': u'http://www.swissmilk.ch',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 308.0,
                    u'Response Time': 3,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'berta',
                    u'Destination': u'http://www.bricklive.ch',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 308.0,
                    u'Response Time': 2,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'uschi',
                    u'Destination': u'http://www.safeatwork.ch/startseite.html',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--veroffentlicht',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 308.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'alfred',
                    u'Destination': u'https://www.lego.com/de-ch/404',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--entwurf',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 404.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'anneliese',
                    u'Destination': u'https://list25.com/404',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 404.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            {
                    u'Origin': u'portal',
                    'responsible': nan,
                    u'Creator': u'fritz',
                    u'Destination': u'https://brettterpstra.com/2018/',
                    'is_done': False,
                    u'Error Message': u'No error occurred',
                    u'Review State': u'bl_workflow--STATUS--arbeitskopie',
                    u'Content Type': u'Unknown content type',
                    u'Status Code': 404.0,
                    u'Response Time': 1,
                    u'Internal/External': u'External',
                    },
            ]
    }
